<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Import-the-source-code-of-the-project" data-toc-modified-id="Import-the-source-code-of-the-project-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Import the source code of the project</a></span></li><li><span><a href="#Import-and-use-the-functionality" data-toc-modified-id="Import-and-use-the-functionality-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Import and use the functionality</a></span></li></ul></div>


# Development with the notebook
This notebook server can be used as a scratchpad. Work in progress code, algorithms, visualizations, tests, ...

The ultimate goal here is to refactor these snippets in well documented and tested python classes and methods so they can be imported easily. 

The suggested workflow is as follows:
1. Use the notebook to prototype and test drive your development
2. Migrate your developed code into the project. Create a python file, organize it in classes,...
3. Document your migrated code (docstring) so it's functionality is documented in the sphinx docs.
4. Import the migrated code back into this notebook and develop tests around it.
5. Include these tests in the project.
6. Cleanup your notebook as the functionality is now in the python project and can be easily imported in the future.


## Import the source code of the project
Updates to the project's source need to be reflected here so it's possible to add new functionality and fix bugs which are directly reflected here. Jupyter supports this behaviour with the `autoreload` magic. 

The 2 cells below will setup this autoreload functionality (so the original import is not cached) and add the project path to the system path. Now the project source can be imported (without installing it as a python package).


In [1]:
%load_ext autoreload
%autoreload 2
# %matplotlib inline


In [2]:
import datetime as dt
import os
import platform
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objs as go

PROJECT_PATH = os.path.dirname(os.getcwd())
print(f'PROJECT_PATH = {PROJECT_PATH}')

if not PROJECT_PATH in sys.path:
    sys.path.append(PROJECT_PATH)
    
print('Platform:', platform.platform())
print('Python version:', sys.version)
print('numpy version:', np.__version__)
np.set_printoptions(threshold=sys.maxsize)


PROJECT_PATH = /home/pietro/Code
Platform: Linux-6.17.0-35-generic-x86_64-with-glibc2.39
Python version: 3.13.13 (main, May 10 2026, 19:26:54) [Clang 22.1.3 ]
numpy version: 2.2.6


In [3]:
#matplotlib tweaking
plt.rcParams['figure.figsize'] = (10.5/2.514/0.7, 4.5/2.514/0.7)
plt.rcParams["font.family"] = "Sans"
plt.rcParams["font.size"] = 10
# plt.rcParams["axes.grid"] = True
# plt.rcParams['grid.color'] = "#CCCCCC"
# plt.rcParams['grid.linestyle'] = "-"
# plt.rcParams['grid.color'] = "#DDDDDD"
# plt.rcParams['grid.linestyle'] = "-"
plt.rcParams['axes.spines.right'] = False
plt.rcParams['axes.spines.top'] = False
plt.rcParams['lines.markersize'] = 3
plt.rcParams['xtick.bottom'] = False
plt.rcParams['xtick.labelbottom'] = True
plt.rcParams['ytick.left'] = False
plt.rcParams['ytick.labelleft'] = True


## Import and use the functionality


In [4]:
# Use the package
import py_fatigue as pf
import py_fatigue.cycle_count.rainflow as rf
import py_fatigue.cycle_count.histogram as ht
from py_fatigue.version import parse_version, __version__
v = parse_version(__version__)


In [5]:
print(v)


Version(major=2, minor=1, patch=0, release=None, num=None)


In [6]:

s = np.array([4,7,2,10,5,9,3,4,2,12,5,11,1,4,3,10,6,12,4,8,1,9,4,6], dtype=float)
# s = [0, 5, 0, 5, 0, 5, 0, 0 , 5, 0, 5, 0, 5, 0]
cc_4p = rf.rainflow(s, method='fourpoint', extended_output=True)
cc_astm = rf.rainflow(s, method='astm', extended_output=True)
display(cc_4p)
display(cc_astm)


(array([[ 2. ,  7. ,  1. ,  4. ,  2. ],
        [ 0.5,  3.5,  1. ,  6. ,  2. ],
        [ 4. ,  6. ,  1. ,  3. , 10. ],
        [ 3. ,  8. ,  1. , 10. ,  2. ],
        [ 0.5,  3.5,  1. , 13. ,  2. ],
        [ 2. ,  8. ,  1. , 15. ,  2. ],
        [ 2. ,  6. ,  1. , 18. ,  2. ],
        [ 5.5,  6.5,  1. , 12. , 10. ],
        [ 1.5,  5.5,  0.5,  0. ,  2. ],
        [ 2.5,  4.5,  0.5,  1. ,  2. ],
        [ 5. ,  7. ,  0.5,  2. , 14. ],
        [ 5.5,  6.5,  0.5,  9. , 22. ],
        [ 4. ,  5. ,  0.5, 20. ,  2. ],
        [ 2.5,  6.5,  0.5, 21. ,  2. ],
        [ 1. ,  5. ,  0.5, 22. ,  2. ]]),
 array([ 4.,  7.,  2., 12.,  1.,  9.,  4.,  6.]),
 array([ 0,  1,  2,  9, 20, 21, 22, 23]))


(array([[ 1.5,  5.5,  0.5,  0. ,  2. ],
        [ 2.5,  4.5,  0.5,  1. ,  2. ],
        [ 2. ,  7. ,  1. ,  4. ,  2. ],
        [ 0.5,  3.5,  1. ,  6. ,  2. ],
        [ 4. ,  6. ,  0.5,  2. ,  2. ],
        [ 4. ,  6. ,  0.5,  3. , 10. ],
        [ 3. ,  8. ,  1. , 10. ,  2. ],
        [ 5. ,  7. ,  0.5,  8. ,  2. ],
        [ 0.5,  3.5,  1. , 13. ,  2. ],
        [ 2. ,  8. ,  1. , 15. ,  2. ],
        [ 5.5,  6.5,  0.5,  9. ,  6. ],
        [ 2. ,  6. ,  1. , 18. ,  2. ],
        [ 5.5,  6.5,  0.5, 12. , 10. ],
        [ 5.5,  6.5,  0.5, 17. ,  6. ],
        [ 4. ,  5. ,  0.5, 20. ,  2. ],
        [ 2.5,  6.5,  0.5, 21. ,  2. ],
        [ 1. ,  5. ,  0.5, 22. ,  2. ]]),
 array([ 4.,  7.,  2., 10.,  2., 12.,  1., 12.,  1.,  9.,  4.,  6.]),
 array([ 0,  1,  2,  3,  8,  9, 12, 17, 20, 21, 22, 23]))


In [14]:
from py_fatigue.material import sn_curve as sn
#SN curves definition
b1_c = sn.SNCurve(
    slope=3,                       # SNCurve can handle multiple slope and
    intercept=12.436,              # intercept types, as long as their sizes 
    norm='DNVGL-RP-C203',          # are compatible. The slope and intercept 
    environment='Free corrosion',  # attribute will be stored as numpy arrays.
    curve='B1'
)
c_c = sn.SNCurve(
    [3],
    12.115,
    norm='DNVGL-RP-C203',
    environment='Free corrosion',
    curve='C'
)
e_c = sn.SNCurve(
    3,
    intercept=[11.533,],
    norm='DNVGL-RP-C203',
    environment='Free corrosion',
    curve='E'
)
w3_c = sn.SNCurve(
    [3],
    intercept=[10.493,],
    norm='DNVGL-RP-C203',
    environment='Free corrosion',
    curve="W3-C"
)

#%%


In [12]:
c_c
