<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
%load_ext autoreload
%autoreload 2
# %matplotlib inline

In [2]:
import datetime as dt
import os
import platform
import sys
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import plotly.graph_objs as go

PROJECT_PATH = os.path.dirname(os.getcwd())
print(f'PROJECT_PATH = {PROJECT_PATH}')

if not PROJECT_PATH in sys.path:
    sys.path.append(PROJECT_PATH)
    
print('Platform:', platform.platform())
print('Python version:', sys.version)
print('numpy version:', np.__version__)
np.set_printoptions(threshold=sys.maxsize)

PROJECT_PATH = C:\Users\pietr\Documents\Azure\py_fatigue
Platform: Windows-10-10.0.25120-SP0
Python version: 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
numpy version: 1.21.5


In [3]:
#matplotlib tweaking
plt.rcParams['figure.figsize'] = (10.5/2.514/0.7, 4.5/2.514/0.7)
plt.rcParams["font.family"] = "Sans"
plt.rcParams["font.size"] = 10
plt.rcParams["axes.grid"] = True
plt.rcParams['grid.color'] = "#CCCCCC"
plt.rcParams['grid.linestyle'] = "-"
plt.rcParams['grid.color'] = "#DDDDDD"
plt.rcParams['grid.linestyle'] = "-"
plt.rcParams['axes.spines.right'] = False
plt.rcParams['axes.spines.top'] = False
plt.rcParams['lines.markersize'] = 3
plt.rcParams['xtick.bottom'] = False
plt.rcParams['xtick.labelbottom'] = True
plt.rcParams['ytick.left'] = False
plt.rcParams['ytick.labelleft'] = True

In [4]:
import py_fatigue.utils as pu

In [47]:
# test_bin_upper_bound
pu.bin_upper_bound(-10, 5, 100.5)  # 105
pu.bin_upper_bound(60, 6, -20)  # -18
pu.bin_upper_bound(60, 6, 60)  # 60
pu.bin_upper_bound(0, 1, 99)  # 99
pu.bin_upper_bound(0, 1, 98.9)  # 99

# pu.bin_upper_bound(1, 3, 2)  # 99


99.0

In [38]:
# calc_bin_edges
pu.calc_bin_edges(1, 2, 3)  # 1
# pu.calc_bin_edges(1, -1, 3)  # empty
# pu.calc_bin_edges(1,10, 1)  # 10
# pu.calc_bin_edges(1,10.1, 1)  # 11
# pu.calc_bin_edges(1,10.1, 0.5)  # 10.5
# pu.calc_bin_edges(1.1,10.1, 0.2)  # 10.1

array([1., 4.])

In [35]:
pu.split_full_cycles_and_residuals(np.hstack([arr_1, [np.nan]]))

C:\Users\pietr\Documents\Azure\py_fatigue\py_fatigue\utils.py:379: RuntimeWarning: invalid value encountered in remainder
  Left edge of the first bin


(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),
 array([], dtype=int64))

In [51]:
# test_split_full_cycles_and_residuals

arr_1 = np.asarray([1, 2, 6, 8, 7, 7, 14, 2,  9, 4, 3], dtype=float)
arr_2 = np.insert(arr_1, [0, 1, 4], 0.5)
arr_3 = np.insert(arr_1, [-1, -1, -1], 0.5)
arr_4 = np.append(arr_1, [0.5, 0.5, 0.5, 0.5, 0.5])
arr_5 = np.hstack([arr_1, [np.nan]])
pu.split_full_cycles_and_residuals(arr_1)  # (array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64), array([], dtype=int64))
pu.split_full_cycles_and_residuals(arr_2)  # (array([ 1,  3,  4,  5,  7,  8,  9, 10, 11, 12], dtype=int64), array([0, 2, 6], dtype=int64))
pu.split_full_cycles_and_residuals(arr_3)  # (array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 12], dtype=int64), array([ 9, 10, 11], dtype=int64))
pu.split_full_cycles_and_residuals(arr_4)  # (array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64), array([10, 11, 12, 13, 14], dtype=int64))

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),
 array([11, 12, 13, 14, 15], dtype=int64))

In [53]:
pu.calc_half_cycles(np.arange(1, len(arr_1) + 1, 1), arr_1)  # array([], dtype=int32)
pu.calc_half_cycles(np.arange(1, len(arr_2) + 1, 1), arr_2)  # array([1, 3, 7])
# pu.calc_half_cycles(np.arange(1, len(arr_3) + 1, 1), arr_3)  # array([10, 11, 12])
# pu.calc_half_cycles(np.arange(1, len(arr_4) + 1, 1), arr_4)  # array([11, 12, 13, 14, 15])
pu.calc_half_cycles(np.arange(1, len(arr_5) + 1, 1), arr_5)  # array([11, 12, 13, 14, 15])

C:\Users\pietr\Documents\Azure\py_fatigue\py_fatigue\utils.py:379: RuntimeWarning: invalid value encountered in remainder
  full_idx = np.where((split[:, 1] % 1 == 0) & (split[:, 1] > 0))[0]


array([], dtype=int32)

In [58]:
pu.calc_full_cycles(np.arange(1, len(arr_1) + 1, 1), arr_1)  # array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
                                                             #         1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
                                                             #         2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
                                                             #         2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
                                                             #         3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
                                                             #         3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,
                                                             #         4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
                                                             #         4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
                                                             #         4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
                                                             #         4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,
                                                             #         5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
                                                             #         5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
                                                             #         5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,
                                                             #         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
                                                             #         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
                                                             #         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
                                                             #         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
                                                             #         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,
                                                             #         7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
                                                             #         7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,
                                                             #         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
                                                             #         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
                                                             #         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
                                                             #         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
                                                             #         9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
                                                             #        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

pu.calc_full_cycles(np.arange(1, len(arr_2) + 1, 1), arr_2)  # array([ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
#                                                              #         2,  2,  2,  2,  2,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
#                                                              #         4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
#                                                              #         4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
#                                                              #         5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
#                                                              #         5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,
#                                                              #         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
#                                                              #         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
#                                                              #         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
#                                                              #         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  8,
#                                                              #         8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
#                                                              #         8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
#                                                              #         8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,
#                                                              #         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
#                                                              #         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
#                                                              #         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
#                                                              #         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
#                                                              #         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10,
#                                                              #         10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
#                                                              #         10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12,
#                                                              #         12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
#                                                              #         12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
#                                                              #         12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
#                                                              #         12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
#                                                              #         12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
#                                                              #         13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13])

pu.calc_full_cycles(np.arange(1, len(arr_3) + 1, 1), arr_3)  # array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
#                                                              #         1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
#                                                              #         2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
#                                                              #         2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
#                                                              #         3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
#                                                              #         3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,
#                                                              #         4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
#                                                              #         4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
#                                                              #         4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
#                                                              #         4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,
#                                                              #         5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
#                                                              #         5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
#                                                              #         5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,
#                                                              #         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
#                                                              #         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
#                                                              #         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
#                                                              #         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
#                                                              #         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,
#                                                              #         7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
#                                                              #         7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,
#                                                              #         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
#                                                              #         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
#                                                              #         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
#                                                              #         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
#                                                              #         9,  9,  9,  9, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
#                                                              #        13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13])
pu.calc_full_cycles(np.arange(1, len(arr_5) + 1, 1), arr_5)  # array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
#                                                              #         1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
#                                                              #         2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
#                                                              #         2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
#                                                              #         3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
#                                                              #         3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,
#                                                              #         4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
#                                                              #         4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
#                                                              #         4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
#                                                              #         4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,
#                                                              #         5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
#                                                              #         5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
#                                                              #         5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,
#                                                              #         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
#                                                              #         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
#                                                              #         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
#                                                              #         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
#                                                              #         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,
#                                                              #         7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
#                                                              #         7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,
#                                                              #         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
#                                                              #         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
#                                                              #         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
#                                                              #         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
#                                                              #         9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
#                                                              #        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

array([ 1,  2,  2,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  4,
        5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  9,  9,  9,  9,
        9,  9,  9,  9,  9, 10, 10, 10, 10, 11, 11, 11])

In [ ]:
pu.calc_full_cycles(np.arange(1, len(arr_3) + 1, 1), arr_3) array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,
        9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
        9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
        9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
        9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
        9,  9,  9,  9, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
       13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13])

In [15]:
s1 = pu.FatigueStress(_counts=arr_1, _values=np.arange(1, len(arr_1) + 1, 1), bin_width=0.5)

In [32]:
print('s1.bin_lb', s1.bin_lb)
print('s1.bin_ub', s1.bin_ub)
print('s1.bin_centers', s1.bin_centers)
print('s1.bin_edges', s1.bin_edges)
print('s1.counts', s1.counts)
print('s1.values', s1.values)
print('s1.full', s1.full)
print('s1.half', s1.half)
print('s1.bins_idx', s1.bins_idx)
print('s1.binned_values', s1.binned_values)

s1.bin_lb 0.75
s1.bin_ub 10.25
s1.bin_centers [ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]
s1.bin_edges [ 0.75  1.25  1.75  2.25  2.75  3.25  3.75  4.25  4.75  5.25  5.75  6.25
  6.75  7.25  7.75  8.25  8.75  9.25  9.75 10.25]
s1.counts [22. 36. 38. 73. 47. 84. 29.  9. 74. 30.]
s1.values [ 1  2  3  4  5  6  7  8  9 10]
s1.full [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  2
  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2
  2  2  2  2  2  2  2  2  2  2  3  3  3  3  3  3  3  3  3  3  3  3  3  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
  4  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5
  5  5  5  5  5  5  5  5  5  5  5 

In [25]:
s1.full_counts

array([22., 36., 38., 73., 47., 84., 29.,  9., 74., 30.])

In [31]:
s1.half_counts

array([], dtype=float64)

74

In [16]:
# from hypothesis import  given, strategies as hy
# Standard imports
from contextlib import nullcontext
from typing import Any, Union, Callable, Tuple
from unittest.mock import Mock

import pytest
import warnings

# Non-standard imports
import numpy as np

import py_fatigue.utils as pu

pu.UnionOfIntArray

# from hypothesis import  given, strategies as hy

def expected(x) -> Tuple[Any, nullcontext]:
    """Mocking function for pytest.mark.parametrize. Expected value"""
    return x, nullcontext()


def error(*args: Any, **kwargs: Any) -> None:
    """Mocking function for pytest.mark.parametrize. Error handling"""
    return Mock(), pytest.raises(*args, **kwargs)


COUNTS_1 = np.array([1, 2, 6, 8, 7, 7, 14, 2,  9, 4, 3], dtype=float)
EXPECTED_1 = (
    np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=np.int64),
    np.array([], dtype=np.int64)
) 
COUNTS_2 = np.insert(COUNTS_1, [0, 1, 4], 0.5)
EXPECTED_2 = (
    np.array([ 1,  3,  4,  5,  7,  8,  9, 10, 11, 12, 13], dtype=np.int64),
    np.array([0, 2, 6], dtype=np.int64)
)
COUNTS_3 = np.insert(COUNTS_1, [-1, -1, -1], 0.5)
EXPECTED_3 = (
    np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 13], dtype=np.int64),
    np.array([10, 11, 12], dtype=np.int64)
)
COUNTS_4 = np.append(COUNTS_1, [0.5, 0.5, 0.5, 0.5, 0.5])
EXPECTED_4 = (
    np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=np.int64),
    np.array([11, 12, 13, 14, 15], dtype=np.int64)
)
COUNTS_5 = np.hstack([COUNTS_1, [np.nan]])
EXPECTED_5 = EXPECTED_1
test_names = "counts, expected, error"
test_data = [
    (COUNTS_1, *expected(EXPECTED_1)),
    (COUNTS_2, *expected(EXPECTED_2)),
    (COUNTS_3, *expected(EXPECTED_3)),
    (COUNTS_4, *expected(EXPECTED_4)),
    (COUNTS_4, *error(RuntimeWarning, match="invalid value encountered")),
]


@pytest.mark.parametrize(test_names, test_data)
def test_split_full_cycles_and_residuals(
    counts: np.ndarray,
    expected: tuple,
    error: Callable,
) -> None:
    """Test split_full_cycles_and_residuals function"""

    with error:
        calculated_output = pu.split_full_cycles_and_residuals(counts)
        assert np.all(calculated_output[0] == expected[0])
        assert np.all(calculated_output[1] == expected[1])



In [20]:
np.all(pu.split_full_cycles_and_residuals(COUNTS_1) == EXPECTED_1)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [14]:
pu.split_full_cycles_and_residuals(COUNTS_1)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),
 array([], dtype=int64))

In [15]:
EXPECTED_1

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),
 array([], dtype=int64))